theme: jekyll-theme-slate
lsi: false
safe: true
source: paulpo215.github.io/
incremental: false
highlighter: rouge
title: Game Phylactery 
project_tagline: Open up, and see what awaits you inside
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
